/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRenderVideoRouteImport } from './routes/api.render-video'
import { Route as ApiRegenerateImageRouteImport } from './routes/api.regenerate-image'
import { Route as ApiRedditRouteImport } from './routes/api.reddit'
import { Route as ApiGenerateScriptRouteImport } from './routes/api.generate-script'
import { Route as ApiGenerateMetadataRouteImport } from './routes/api.generate-metadata'
import { Route as ApiGenerateImagesRouteImport } from './routes/api.generate-images'
import { Route as ApiGenerateAudioRouteImport } from './routes/api.generate-audio'
import { Route as ApiRenderProgressScriptIdRouteImport } from './routes/api.render-progress.$scriptId'
import { Route as ApiImageStatusScriptIdRouteImport } from './routes/api.image-status.$scriptId'
import { Route as ApiMediaScriptIdVideoFileNameRouteImport } from './routes/api.media.$scriptId.video.$fileName'
import { Route as ApiMediaScriptIdImagesFileNameRouteImport } from './routes/api.media.$scriptId.images.$fileName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderVideoRoute = ApiRenderVideoRouteImport.update({
  id: '/api/render-video',
  path: '/api/render-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegenerateImageRoute = ApiRegenerateImageRouteImport.update({
  id: '/api/regenerate-image',
  path: '/api/regenerate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditRoute = ApiRedditRouteImport.update({
  id: '/api/reddit',
  path: '/api/reddit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateScriptRoute = ApiGenerateScriptRouteImport.update({
  id: '/api/generate-script',
  path: '/api/generate-script',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateMetadataRoute = ApiGenerateMetadataRouteImport.update({
  id: '/api/generate-metadata',
  path: '/api/generate-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImagesRoute = ApiGenerateImagesRouteImport.update({
  id: '/api/generate-images',
  path: '/api/generate-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateAudioRoute = ApiGenerateAudioRouteImport.update({
  id: '/api/generate-audio',
  path: '/api/generate-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderProgressScriptIdRoute =
  ApiRenderProgressScriptIdRouteImport.update({
    id: '/api/render-progress/$scriptId',
    path: '/api/render-progress/$scriptId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiImageStatusScriptIdRoute = ApiImageStatusScriptIdRouteImport.update({
  id: '/api/image-status/$scriptId',
  path: '/api/image-status/$scriptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaScriptIdVideoFileNameRoute =
  ApiMediaScriptIdVideoFileNameRouteImport.update({
    id: '/api/media/$scriptId/video/$fileName',
    path: '/api/media/$scriptId/video/$fileName',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMediaScriptIdImagesFileNameRoute =
  ApiMediaScriptIdImagesFileNameRouteImport.update({
    id: '/api/media/$scriptId/images/$fileName',
    path: '/api/media/$scriptId/images/$fileName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-audio': typeof ApiGenerateAudioRoute
  '/api/generate-images': typeof ApiGenerateImagesRoute
  '/api/generate-metadata': typeof ApiGenerateMetadataRoute
  '/api/generate-script': typeof ApiGenerateScriptRoute
  '/api/reddit': typeof ApiRedditRoute
  '/api/regenerate-image': typeof ApiRegenerateImageRoute
  '/api/render-video': typeof ApiRenderVideoRoute
  '/api/image-status/$scriptId': typeof ApiImageStatusScriptIdRoute
  '/api/render-progress/$scriptId': typeof ApiRenderProgressScriptIdRoute
  '/api/media/$scriptId/images/$fileName': typeof ApiMediaScriptIdImagesFileNameRoute
  '/api/media/$scriptId/video/$fileName': typeof ApiMediaScriptIdVideoFileNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-audio': typeof ApiGenerateAudioRoute
  '/api/generate-images': typeof ApiGenerateImagesRoute
  '/api/generate-metadata': typeof ApiGenerateMetadataRoute
  '/api/generate-script': typeof ApiGenerateScriptRoute
  '/api/reddit': typeof ApiRedditRoute
  '/api/regenerate-image': typeof ApiRegenerateImageRoute
  '/api/render-video': typeof ApiRenderVideoRoute
  '/api/image-status/$scriptId': typeof ApiImageStatusScriptIdRoute
  '/api/render-progress/$scriptId': typeof ApiRenderProgressScriptIdRoute
  '/api/media/$scriptId/images/$fileName': typeof ApiMediaScriptIdImagesFileNameRoute
  '/api/media/$scriptId/video/$fileName': typeof ApiMediaScriptIdVideoFileNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-audio': typeof ApiGenerateAudioRoute
  '/api/generate-images': typeof ApiGenerateImagesRoute
  '/api/generate-metadata': typeof ApiGenerateMetadataRoute
  '/api/generate-script': typeof ApiGenerateScriptRoute
  '/api/reddit': typeof ApiRedditRoute
  '/api/regenerate-image': typeof ApiRegenerateImageRoute
  '/api/render-video': typeof ApiRenderVideoRoute
  '/api/image-status/$scriptId': typeof ApiImageStatusScriptIdRoute
  '/api/render-progress/$scriptId': typeof ApiRenderProgressScriptIdRoute
  '/api/media/$scriptId/images/$fileName': typeof ApiMediaScriptIdImagesFileNameRoute
  '/api/media/$scriptId/video/$fileName': typeof ApiMediaScriptIdVideoFileNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/generate-audio'
    | '/api/generate-images'
    | '/api/generate-metadata'
    | '/api/generate-script'
    | '/api/reddit'
    | '/api/regenerate-image'
    | '/api/render-video'
    | '/api/image-status/$scriptId'
    | '/api/render-progress/$scriptId'
    | '/api/media/$scriptId/images/$fileName'
    | '/api/media/$scriptId/video/$fileName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/generate-audio'
    | '/api/generate-images'
    | '/api/generate-metadata'
    | '/api/generate-script'
    | '/api/reddit'
    | '/api/regenerate-image'
    | '/api/render-video'
    | '/api/image-status/$scriptId'
    | '/api/render-progress/$scriptId'
    | '/api/media/$scriptId/images/$fileName'
    | '/api/media/$scriptId/video/$fileName'
  id:
    | '__root__'
    | '/'
    | '/api/generate-audio'
    | '/api/generate-images'
    | '/api/generate-metadata'
    | '/api/generate-script'
    | '/api/reddit'
    | '/api/regenerate-image'
    | '/api/render-video'
    | '/api/image-status/$scriptId'
    | '/api/render-progress/$scriptId'
    | '/api/media/$scriptId/images/$fileName'
    | '/api/media/$scriptId/video/$fileName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateAudioRoute: typeof ApiGenerateAudioRoute
  ApiGenerateImagesRoute: typeof ApiGenerateImagesRoute
  ApiGenerateMetadataRoute: typeof ApiGenerateMetadataRoute
  ApiGenerateScriptRoute: typeof ApiGenerateScriptRoute
  ApiRedditRoute: typeof ApiRedditRoute
  ApiRegenerateImageRoute: typeof ApiRegenerateImageRoute
  ApiRenderVideoRoute: typeof ApiRenderVideoRoute
  ApiImageStatusScriptIdRoute: typeof ApiImageStatusScriptIdRoute
  ApiRenderProgressScriptIdRoute: typeof ApiRenderProgressScriptIdRoute
  ApiMediaScriptIdImagesFileNameRoute: typeof ApiMediaScriptIdImagesFileNameRoute
  ApiMediaScriptIdVideoFileNameRoute: typeof ApiMediaScriptIdVideoFileNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render-video': {
      id: '/api/render-video'
      path: '/api/render-video'
      fullPath: '/api/render-video'
      preLoaderRoute: typeof ApiRenderVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/regenerate-image': {
      id: '/api/regenerate-image'
      path: '/api/regenerate-image'
      fullPath: '/api/regenerate-image'
      preLoaderRoute: typeof ApiRegenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit': {
      id: '/api/reddit'
      path: '/api/reddit'
      fullPath: '/api/reddit'
      preLoaderRoute: typeof ApiRedditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-script': {
      id: '/api/generate-script'
      path: '/api/generate-script'
      fullPath: '/api/generate-script'
      preLoaderRoute: typeof ApiGenerateScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-metadata': {
      id: '/api/generate-metadata'
      path: '/api/generate-metadata'
      fullPath: '/api/generate-metadata'
      preLoaderRoute: typeof ApiGenerateMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-images': {
      id: '/api/generate-images'
      path: '/api/generate-images'
      fullPath: '/api/generate-images'
      preLoaderRoute: typeof ApiGenerateImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-audio': {
      id: '/api/generate-audio'
      path: '/api/generate-audio'
      fullPath: '/api/generate-audio'
      preLoaderRoute: typeof ApiGenerateAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render-progress/$scriptId': {
      id: '/api/render-progress/$scriptId'
      path: '/api/render-progress/$scriptId'
      fullPath: '/api/render-progress/$scriptId'
      preLoaderRoute: typeof ApiRenderProgressScriptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-status/$scriptId': {
      id: '/api/image-status/$scriptId'
      path: '/api/image-status/$scriptId'
      fullPath: '/api/image-status/$scriptId'
      preLoaderRoute: typeof ApiImageStatusScriptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$scriptId/video/$fileName': {
      id: '/api/media/$scriptId/video/$fileName'
      path: '/api/media/$scriptId/video/$fileName'
      fullPath: '/api/media/$scriptId/video/$fileName'
      preLoaderRoute: typeof ApiMediaScriptIdVideoFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$scriptId/images/$fileName': {
      id: '/api/media/$scriptId/images/$fileName'
      path: '/api/media/$scriptId/images/$fileName'
      fullPath: '/api/media/$scriptId/images/$fileName'
      preLoaderRoute: typeof ApiMediaScriptIdImagesFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateAudioRoute: ApiGenerateAudioRoute,
  ApiGenerateImagesRoute: ApiGenerateImagesRoute,
  ApiGenerateMetadataRoute: ApiGenerateMetadataRoute,
  ApiGenerateScriptRoute: ApiGenerateScriptRoute,
  ApiRedditRoute: ApiRedditRoute,
  ApiRegenerateImageRoute: ApiRegenerateImageRoute,
  ApiRenderVideoRoute: ApiRenderVideoRoute,
  ApiImageStatusScriptIdRoute: ApiImageStatusScriptIdRoute,
  ApiRenderProgressScriptIdRoute: ApiRenderProgressScriptIdRoute,
  ApiMediaScriptIdImagesFileNameRoute: ApiMediaScriptIdImagesFileNameRoute,
  ApiMediaScriptIdVideoFileNameRoute: ApiMediaScriptIdVideoFileNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
